Web/Portal/Controllers/FerramentasController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProgramadorFajuto.Application.Aplicacao.Portal.Contratos;

namespace ProgramadorFajuto.Web.Portal.Controllers
{
    public class FerramentasController : Controller
    {
        private readonly IServicoDeFerramentas _servicoDeFerramentas;

        public FerramentasController(IServicoDeFerramentas servicoDeFerramentas)
        {
            this._servicoDeFerramentas = servicoDeFerramentas;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return this.View();
        }

        [HttpGet]
        public IActionResult FormatarEmailMarketing()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult FormatarEmailMarketing(IFormFile arquivo)
        {
            return File(this._servicoDeFerramentas.Formatar(arquivo), "application/file", "EmailFormatado.html");
        }
    }
}

Web/Portal/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProgramadorFajuto.Application.Aplicacao.Portal.Contratos;
using ProgramadorFajuto.Application.Aplicacao.Portal.Modelos;
using ProgramadorFajuto.Application.Aplicacao.Util.Modelos.Base;
using ProgramadorFajuto.Domain.Dominio.Entidades;
using ProgramadorFajuto.Web.Portal.Filters;

namespace ProgramadorFajuto.Web.Portal.Controllers
{
    public class HomeController : Controller
    {
        private IServicoDeHome _servicoDeHome;

        public HomeController(IServicoDeHome servicoDeHome) => this._servicoDeHome = servicoDeHome;

        [HttpGet]
        [ExcecoesFilter]
        public IActionResult Index(int? pagina)
        {
            var posts = this._servicoDeHome.ListarPosts();
            var postsMaisPopulares = this._servicoDeHome.ListarPostsMaisPopulares(posts);

            return View(new ModeloDeHome(ModeloDeLista<Post>.Criar(posts, pagina ?? 1), postsMaisPopulares));
        }
    }
}

Web/Portal/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProgramadorFajuto.Application.Aplicacao.Portal.Contratos;
using ProgramadorFajuto.Application.Aplicacao.Portal.Modelos;
using ProgramadorFajuto.Web.Portal.Extensions;
using ProgramadorFajuto.Web.Portal.Filters;
using System.Threading.Tasks;

namespace ProgramadorFajuto.Web.Portal.Controllers
{
    public class LoginController : Controller
    {
        private readonly IServicoDeLogin _servicoDeLogin;

        public LoginController(IServicoDeLogin servicoDeLogin)
        {
            this._servicoDeLogin = servicoDeLogin;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return this.View();
        }

        [HttpGet]
        public IActionResult Cadastro()
        {
            return this.View();
        }

        [HttpPost]
        [ExcecoesFilter]
        public async Task<IActionResult> Autenticar(ModeloDeLogin modeloDeLogin, string returnUrl = null)
        {
            await this._servicoDeLogin.AutenticarAsync(modeloDeLogin);

            if (!string.IsNullOrEmpty(returnUrl))
                return Redirect(returnUrl);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Authorize]
        [ExcecoesFilter]
        public async Task<IActionResult> Deslogar()
        {
            await this._servicoDeLogin.DeslogarAsync();

            return RedirectToAction("Index", "Login");
        }

        [HttpPost]
        [ExcecoesFilter]
        public async Task<IActionResult> Cadastrar(string nome, string email, string senha)
        {
            await this._servicoDeLogin.CadastrarAsync(nome, email, senha);

            this.AdicionarMensagemDeSucesso("Você se cadastrou com sucesso, Bem vindo!");

            return RedirectToAction("Index", "Home");
        }
    }
}

Web/Portal/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using ProgramadorFajuto.Application.Aplicacao.Portal.Contratos;
using ProgramadorFajuto.Application.Aplicacao.Portal.Modelos;
using ProgramadorFajuto.Domain.Dominio.Entidades;
using ProgramadorFajuto.Web.Portal.Filters;
using System.Collections.Generic;
using System.Linq;

namespace ProgramadorFajuto.Web.Portal.Controllers
{
    public class PostController : Controller
    {
        private readonly IServicoDePost _servicoDePost;

        public PostController(IServicoDePost servicoDePost)
        {
            this._servicoDePost = servicoDePost;
        }

        [HttpGet]
        [ExcecoesFilter]
        public IActionResult Index()
        {
            var posts = this._servicoDePost.ListarPosts();
            var meusPosts = new List<Post>();

            if (User.Identity.IsAuthenticated)
                meusPosts = posts.Where(p => p.Id == int.Parse(User.FindFirst("Id").Value)).ToList();

            return View(new ModeloDePost(posts, meusPosts));
        }

        [HttpGet]
        [ExcecoesFilter]
        public IActionResult Detalhes(int id)
        {
            var post = this._servicoDePost.ObterPostPorId(id);

            return View(post);
        }
    }
}

Web/Portal/Views/Ferramentas/FormatarEmailMarketing.cshtml
@{
    ViewData["Title"] = "Formatar Email Marketing";
}

<div id="content">
    <div class="container">
        <div class="white">
            <div class="conteudo">
                <form asp-controller="Ferramentas" asp-action="FormatarEmailMarketing" enctype="multipart/form-data">
                    <label>Arquivo .html</label>
                    <input type="file" name="arquivo" multiple />
                    <button type="submit" class="btn"><b>Enviar</b></button>
                </form>
            </div>
        </div>
    </div>
</div>

Web/Portal/Views/Ferramentas/Index.cshtml
@{
    ViewData["Title"] = "Ferramentas";
}

<div id="content">
    <div class="container">
        <div class="white">
            <div class="conteudo">
                <a href="@Url.Action("FormatarEmailMarketing", "Ferramentas")">Ferramenta de recorte de e-mail marketing</a>
            </div>
        </div>
    </div>
</div>

Web/Portal/Views/Home/Index.cshtml
@model ModeloDeHome
@{
    ViewData["Title"] = "Home";
}

<div id="content">
    <div class="container">
        <div class="row">
            <div class="col-xl-8 col-lg-8 col-md-8 col-sm-12 col-xs-12">
                @foreach (var post in Model.Posts)
            {
                    <section class="white">
                        <div class="post-cabecalho">
                            <ul>
                                @foreach (var tag in post.Tags)
                                {
                                    <li class="tag-cabecalho @tag.Valor"><h1 class="center-block">@tag.Valor</h1></li>
                                }
                            </ul>
                        </div>
                        <div class="conteudo">
                            <h3 class="text-uppercase"><b>@post.Titulo</b></h3>
                        </div>
                        <div class="conteudo">
                            <span class="opacity">em @post.Inclusao.ToString("dd \\de MMMM \\de yyyy")</span>, por @post.Autor.Nome
                        </div>
                        <div class="conteudo">
                            <h5>@post.Descricao</h5>
                        </div>
                        <div class="conteudo">
                            @(Html.Raw(post.Conteudo.Substring(0, post.Conteudo.Length > 360 ? 360 : post.Conteudo.Length) + " [...]"))
                        </div>
                        <div class="conteudo">
                            <div class="row">
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                    <a class="button text-capitalize" href="@Url.Action("Detalhes", "Post", new { Id = post.Id })"><b>Continue lendo</b></a>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                    <h3 class="pull-right"><b>Comentarios</b><span class="tag">@post.Comentarios.Count()</span></h3>
                                </div>
                            </div>
                        </div>
                    </section>
                }
                <div class="conteudo text-center">
                    <a href="@Url.Action("Index", "Home", new { pagina = Model.Posts.NumeroDaPagina - 1})" class="button text-capitalize @(Model.Posts.TemPaginaAnterior ? "" : "d-none")"><</a>
                    <a href="@Url.Action("Index", "Home", new { pagina = Model.Posts.NumeroDaPagina + 1})" class="button text-capitalize @(Model.Posts.TemPaginaPosterior ? "" : "d-none")">></a>
                </div>
            </div>
            <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <section class="white">
                    <div class="conteudo cinza">
                        <h4>Posts mais populares</h4>
                    </div>
                    <ul>
                        @foreach (var post in Model.PostsMaisPopulares)
                        {
                            <li class="conteudo">
                                <a href="@Url.Action("Detalhes", "Post", new { id = post.Id })">
                                    <img src="~/img/designer.jpg" alt="@post.Titulo" class="img-responsive rounded-circle" />
                                    <span>@post.Titulo</span><br />
                                    <span>
                                        @foreach (var tag in post.Tags)
                                        {
                                            <i class="tag">@tag.Valor</i>
                                        }
                                    </span>
                                </a>
                            </li>
                        }
                    </ul>
                </section>
            </div>
        </div>
    </div>
</div>

Web/Portal/Views/Login/Cadastro.cshtml
@{
    ViewData["Title"] = "Cadastro";
}

<div id="content">
    <div class="container">
        <section id="cadastro">
            <form asp-controller="Login" asp-action="Cadastrar" method="post" class="mx-auto">
                <label>Nome:</label>
                <input type="text" name="nome" />
                <label>E-mail:</label>
                <input type="text" name="email" />
                <label>Senha:</label>
                <input type="password" name="senha" />
                <button type="submit"><b>Cadastrar</b></button>
            </form>
        </section>
    </div>
</div>

Web/Portal/Views/Login/Index.cshtml
@{
    ViewData["Title"] = "Login";
}

<div id="content">
    <div class="container">
        <section id="login">
            <form asp-controller="Login" asp-action="Autenticar" method="post" class="mx-auto">
                <label>E-mail ou Apelido:</label>
                <input type="text" name="email" />
                <label>Senha:</label>
                <input type="password" name="senha" />
                <button type="submit"><b>Entrar</b></button>
            </form>
        </section>
    </div>
    <section>
        <div class="container text-center">
            <h3>Não possui uma conta? Cadastre-se <a href="@Url.Action("Cadastro", "Login")">Aqui</a>, é free.</h3>
        </div>
    </section>
</div>

Web/Portal/Views/Post/Index.cshtml
@{
    ViewData["Title"] = "Posts";
}

<div id="content">
    <div class="container">
    </div>
</div>

Web/Portal/Views/Shared/_Header.cshtml
<header id="cabecalho">
    <div class="container">
        <div class="row">
            <div class="col-10 col-sm-10 col-md-11 col-lg-11 col-xl-11">
                <div class="text-center" id="boas-vindas">
                    Bem vindo ao <b>Programador Fajuto</b>, <span class="tag">estranho</span>
                </div>
            </div>
            <div class="col-2 col-sm-2 col-md-1 col-lg-1 col-xl-1">
                <a href="#" id="gatilho">
                    Menu
                    <span></span>
                </a>
            </div>
        </div>
    </div>
</header>

Web/Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"]</title>

    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <link rel="manifest" href="~/manifest.json">

    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/animate-css/animate.min.css" rel="stylesheet" />
    <link href="~/lib/sweetalert/dist/sweetalert.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js" async defer asp-append-version="true"></script>
</head>
<body class="carregando">
    @Html.Partial("_Header")

    <main>
        <div id="content">
            @RenderBody()
        </div>
    </main>

    @Html.Partial("_Menu")

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/popper.js/dist/umd/popper.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery-pjax/jquery.pjax.js"></script>
    <script src="~/lib/sweetalert/dist/sweetalert.min.js"></script>
    <script src="~/js/site.js"></script>

    <script src="https://cdn.jsdelivr.net/ga-lite/latest/ga-lite.min.js" async defer asp-append-version="true"></script>
    <script>
        var galite = galite || {};
        galite.UA = 'UA-91931290-1';
    </script>
    <script>
        if ('serviceWorker' in navigator) {
            window.addEventListener('load', function () {
                navigator.serviceWorker.register('/service-worker.js')
                    .then(function (event) {
                        console.log("Service Worker registrado com sucesso.", event);
                    }).catch(function (error) {
                        console.log("Service Worker falhou ao ser registrado.", error)
                    });
            });
        }
    </script>

    @RenderSection("Scripts", required: false)
    @Html.Partial("_Mensagens")
</body>
</html>

Web/Portal/Views/Shared/_Mensagens.cshtml
@if (TempData["Mensagem"] != null)
{
    <script>
        ProgramadorFajuto.AdicionarMensagem("@TempData["Mensagem"]");
    </script>
}

@if (TempData["MensagemDeSucesso"] != null)
{
    <script>
        ProgramadorFajuto.AdicionarMensagemDeSucesso("@TempData["MensagemDeSucesso"]");
    </script>
}

@if (TempData["MensagemDeErro"] != null)
{
    <script>
        ProgramadorFajuto.AdicionarMensagemDeErro("@TempData["MensagemDeErro"]");
    </script>
}

Web/Portal/Views/Shared/_Menu.cshtml
<nav id="nav">
    <ul id="menu">
        <li class="selecionado">
            <a href="@Url.Action("Index", "Home")">Home<img src="~/icons/house.svg" alt="icon-house" /></a>
        </li>
        <li>
            <a href="@Url.Action("Index", "Post")">Post<img src="~/icons/archive.svg" alt="icon-archive" /></a>
        </li>
        <li>
            <a href="@Url.Action("Index", "Ferramentas")">Ferramentas<img src="~/icons/garbage-1.svg" alt="icon-garbage" /></a>
        </li>
        <li>
            <a href="@Url.Action("Index", "Login")">Login<img src="~/icons/login.svg" alt="icon-login" /></a>
        </li>
    </ul>

    <span class="marcador cor-1"></span>
</nav>